### ISSUE TITLE
Unknown Tag

### ISSUE THREAD

**Issue by bobred** [bastula/dicompyler#118]
Hi
Dicompyler crashes when I load a plan with tage 300a,00c5

Platform information:
System: Windows
Version: ('post2008Server', '6.2.9200', '', u'Multiprocessor Free')
Python Version: 2.6.6
dicompyler Version: 0.4.2

dicompyler.plugin: DEBUG: quickopen loaded
dicompyler.plugin: DEBUG: treeview loaded
dicompyler.dicomgui: DEBUG: Reading: N:\ZZZ ARIA TEST AM2_NFCU\RP.1.3.46.670589.13.9054448.20190329084408.759056.dcm
dicompyler: ERROR: Unhandled exception: Traceback (most recent call last):
  File "main.py", line 727, in Run
  File "threading.pyo", line 484, in run
  File "P:\python\dicompyler-bdist\dist\baseplugins\treeview.py", line 156, in RecurseTreeThread
  File "P:\python\dicompyler-bdist\dist\baseplugins\treeview.py", line 156, in RecurseTreeThread
  File "P:\python\dicompyler-bdist\dist\baseplugins\treeview.py", line 135, in RecurseTreeThread
  File "dicom\dataset.pyo", line 322, in __iter__
  File "dicom\dataset.pyo", line 273, in __getitem__
  File "dicom\dataelem.pyo", line 320, in DataElement_from_raw
KeyError: "Unknown DICOM tag (300a, 00c5) - can't look up VR"

dicompyler: ERROR: Unhandled exception: Traceback (most recent call last):
  File "P:\python\dicompyler-bdist\dist\baseplugins\treeview.py", line 129, in OnLoadTree
  File "wx\_core.pyo", line 14568, in __getattr__
PyDeadObjectError: The C++ part of the ProgressDialog object has been deleted, attribute access no longer allowed.

**Comment by bastula** [comment]
Sorry, this is a tag that isn't supported in the released 0.4.2 version of dicompyler as it has an old version of the data dictionary. If you are able to run the source version, it will be able to read the file with this tag.

**Comment by bobred** [comment]
Thanks
