### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lxu3rjpa/dicompyler/

### ISSUE THREAD

**Issue by srmb11** [bastula/dicompyler#126]
I an using ubuntu 18.04 and when I try to install dicompyler using `pip3 install dicompyler` I get  the following error 

`
    Traceback (most recent call last):
      File "/tmp/pip-build-lxu3rjpa/dicompyler/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
`

'    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lxu3rjpa/dicompyler/setup.py", line 11, in <module>
        use_setuptools()
      File "/tmp/pip-build-lxu3rjpa/dicompyler/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-build-lxu3rjpa/dicompyler/distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "/tmp/pip-build-lxu3rjpa/dicompyler/distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required
    
    ----------------------------------------
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lxu3rjpa/dicompyler/
`

**Comment by bastula** [comment]
The version that is released on pip seems to still rely on `distribute`. There are two options currently:
1. Use the dicompyler package provided by debian-med: https://packages.debian.org/sid/dicompyler
2. Download the latest source from GitHub and install from that.

Hope that helps.
