### ISSUE TITLE
Installation failed issue.

### ISSUE THREAD

**Issue by Joevaen** [bastula/dicompyler#134]
Hi, a newbie here.I encountered some problems.
When I installed, `urllib.error.HTTPError: HTTP Error 403: SSL is required`occured.
So I change `DEFAULT_URL = "http://pypi.python.org/packages/source/d/distribute/"`to `DEFAULT_URL = "https://pypi.python.org/packages/source/d/distribute/"`. It worked and error disappeared.
But new error happened
`Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    use_setuptools()
  File "/home/qiao/Software/dicompyler-0.4.2/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/qiao/Software/dicompyler-0.4.2/distribute_setup.py", line 125, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "/home/qiao/Software/dicompyler-0.4.2/distribute_setup.py", line 99, in _build_egg
    _extractall(tar)
  File "/home/qiao/Software/dicompyler-0.4.2/distribute_setup.py", line 467, in _extractall
    self.chown(tarinfo, dirpath)
TypeError: chown() missing 1 required positional argument: 'numeric_owner'
`
What should I do? Thanks a lot!
Best wishes,
Joevaen

**Comment by bastula** [comment]
I believe you are using the latest zip file (0.4.2) from the releases page. Unfortunately, that version still uses `distribute` package which isn't really supported by Python for package management. You could try to install the latest source version instead.

**Comment by Joevaen** [comment]
> I believe you are using the latest zip file (0.4.2) from the releases page. Unfortunately, that version still uses `distribute` package which isn't really supported by Python for package management. You could try to install the latest source version instead.

@bastula Hi Thanks a lot!
I have followed your advice and it worked.But I encountered a new error like below:
![2020-07-01 19-39-14屏幕截图](https://user-images.githubusercontent.com/46133615/86239860-a5f45180-bbd2-11ea-9376-6678f39b28da.png)
What to do for this?

**Comment by renatobellotti** [comment]
I experienced the same issue. In other words, the software is not installable. That's a pity, it looks so promising...

**Comment by renatobellotti** [comment]
I have tried again and found several issues. **This package is broken and seems to be unmaintained. DO NOT USE IT!**

Why?

- The package uploaded to PyPi is from 2014 and contains links to the old repo hosted on Google code.
- I was able to clone and build the package using the code from this repo (``pip install .``). When I start the program, I get the following error:

```
/home/renato/.local/lib/python3.9/site-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '
ERROR: Unhandled exception: Traceback (most recent call last):
  File "/home/renato/.local/lib/python3.9/site-packages/dicompyler/main.py", line 934, in OnInit
    dicompylerFrame = MainFrame(None, -1, "dicompyler", self.res)
  File "/home/renato/.local/lib/python3.9/site-packages/dicompyler/main.py", line 134, in __init__
    hGrid.Add(self.panelGeneral, 1, flag=wx.EXPAND|wx.ALL|wx.ALIGN_CENTRE)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at /tmp/pip-install-u29ibake/wxpython/ext/wxWidgets/src/common/sizer.cpp(2181) in DoInsert(): Vertical alignment flags are ignored with wxEXPAND

OnInit returned false, exiting...
```

**Comment by bastula** [comment]
Looks to be a wxPython 4.1.0 issue. Please use a version less than 4.1.0 but above 4.0. I will update the requirements to pin that version.
