### ISSUE TITLE
Error running from source

### ISSUE THREAD

**Issue by jaceksobiecki** [bastula/dicompyler#138]
I'm having problems with running program from source:

ERROR: Unhandled exception: Traceback (most recent call last):
  File "/Users/jacek/PycharmProjects/dicompyler/dicompyler/main.py", line 934, in OnInit
    dicompylerFrame = MainFrame(None, -1, "dicompyler", self.res)
  File "/Users/jacek/PycharmProjects/dicompyler/dicompyler/main.py", line 132, in __init__
    hGrid.Add(self.panelGeneral, 1, flag=wx.EXPAND|wx.ALL|wx.ALIGN_CENTRE, border=4)
wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at /private/var/folders/bj/69k5zv512g3fcy115cv2n9lh0000gn/T/pip-install-T6R5Me/wxpython/ext/wxWidgets/src/common/sizer.cpp(2184) in DoInsert(): Vertical alignment flags are ignored with wxEXPAND

OnInit returned false, exiting...

Followed by:
<img width="830" alt="bez nazwy" src="https://user-images.githubusercontent.com/26235329/112836961-8f185800-909b-11eb-8099-a07178b1f4eb.png">

I'd appreciate any help.

**Comment by jaceksobiecki** [comment]
The problem was created by using wxPython 4.1.1. Works well on version 4.0.4
