### ISSUE TITLE
Could not install the package

### ISSUE THREAD

**Issue by bjce** [bastula/dicompyler#141]
Hello

First of all thank you very much for the writers and maintainers of the package

I'm really sorry to have to ask this question but I'm trying the file `treeview.py`. I ran `pip install dicompyler` and got several errors: 

```
Collecting dicompyler
  Downloading dicompyler-0.4.2.tar.gz (299 kB)
     |████████████████████████████████| 299 kB 1.5 MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/user/Documents/programming/python/mainenv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_4b39d12cd0c94805858f691d6253cdeb/setup.py'"'"'; __file__='"'"'/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_4b39d12cd0c94805858f691d6253cdeb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-pip-egg-info-11p0ymxx
         cwd: /private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_4b39d12cd0c94805858f691d6253cdeb/
    Complete output (31 lines):
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.26.tar.gz
    Traceback (most recent call last):
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_4b39d12cd0c94805858f691d6253cdeb/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_4b39d12cd0c94805858f691d6253cdeb/setup.py", line 11, in <module>
        use_setuptools()
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_4b39d12cd0c94805858f691d6253cdeb/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_4b39d12cd0c94805858f691d6253cdeb/distribute_setup.py", line 123, in _do_download
        tarball = download_setuptools(version, download_base,
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_4b39d12cd0c94805858f691d6253cdeb/distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2f/b7/9a748e78429b09c16c767c2db1c0fc36efe09290e172a5952f742b903eb0/dicompyler-0.4.2.tar.gz#sha256=f2248d743ea91c11a793419abd893c318fc4c34336d795c0bf9f0ac58e5ffebc (from https://pypi.org/simple/dicompyler/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading dicompyler-0.4.1-1.tar.gz (292 kB)
     |████████████████████████████████| 292 kB 1.7 MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/user/Documents/programming/python/mainenv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_7af82527120a43ba80a3fd3b5f558a76/setup.py'"'"'; __file__='"'"'/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_7af82527120a43ba80a3fd3b5f558a76/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-pip-egg-info-msfi0vmd
         cwd: /private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_7af82527120a43ba80a3fd3b5f558a76/
    Complete output (31 lines):
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.24.tar.gz
    Traceback (most recent call last):
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_7af82527120a43ba80a3fd3b5f558a76/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_7af82527120a43ba80a3fd3b5f558a76/setup.py", line 11, in <module>
        use_setuptools()
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_7af82527120a43ba80a3fd3b5f558a76/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_7af82527120a43ba80a3fd3b5f558a76/distribute_setup.py", line 123, in _do_download
        tarball = download_setuptools(version, download_base,
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_7af82527120a43ba80a3fd3b5f558a76/distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/36/42/a6961bda09012b0d7240ed7aca13a90610824def4868233450bafd184a0e/dicompyler-0.4.1-1.tar.gz#sha256=187a2dc304dca2a722aec5ab33f7ab19dd395cb5f879d1817e834c3db6949cbf (from https://pypi.org/simple/dicompyler/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading dicompyler-0.4.1.tar.gz (146 kB)
     |████████████████████████████████| 146 kB 1.7 MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/user/Documents/programming/python/mainenv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_c6f776a9fb6847a38fcc30bef70f3a4a/setup.py'"'"'; __file__='"'"'/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_c6f776a9fb6847a38fcc30bef70f3a4a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-pip-egg-info-l1z_ezc3
         cwd: /private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_c6f776a9fb6847a38fcc30bef70f3a4a/
    Complete output (31 lines):
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.24.tar.gz
    Traceback (most recent call last):
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_c6f776a9fb6847a38fcc30bef70f3a4a/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_c6f776a9fb6847a38fcc30bef70f3a4a/setup.py", line 11, in <module>
        use_setuptools()
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_c6f776a9fb6847a38fcc30bef70f3a4a/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_c6f776a9fb6847a38fcc30bef70f3a4a/distribute_setup.py", line 123, in _do_download
        tarball = download_setuptools(version, download_base,
      File "/private/var/folders/jq/yyp9q2fs1z5780k9l1_2ph4r0000gn/T/pip-install-tcjy1afu/dicompyler_c6f776a9fb6847a38fcc30bef70f3a4a/distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/91/29/37699708b081249159b0f7472af75553af7be774eab0a4db713e737009b0/dicompyler-0.4.1.tar.gz#sha256=7d53229dc48bc5a94ff951486d33376daafbf95ba61450f0bde2ea5c5484fd07 (from https://pypi.org/simple/dicompyler/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement dicompyler (from versions: 0.4.1, 0.4.1.post1, 0.4.2)
ERROR: No matching distribution found for dicompyler
WARNING: You are using pip version 21.1.3; however, version 21.2.4 is available.
You should consider upgrading via the '/Users/user/Documents/programming/python/mainenv/bin/python3 -m pip install --upgrade pip' command.

```

What shall I do to be able to use `treeview.py`. What am I doing wrong?

Many thanks in advance

**Comment by bastula** [comment]
Do you want to use the `treeview.py` standalone? It needs the full dicompyler application to run. You will probably have better luck installing from source via git, as the latest PyPI package is rather old.

**Comment by bjce** [comment]
many thanks for your answer @bastula. So I would really like to install the whole package from source via git. As I'm not very experienced in the domain and usually install package with `pip install packagename`, I don't how to install code from source. Do you think you can help me by giving the 3-4 (hopefully not more) commands needed for installing the package from source after having downloaded the repo? Many thanks in advance?

**Comment by bastula** [comment]
Once you have downloaded a copy of the source, you can do `pip install -e .` inside the source distribution folder. Another option (which downloads a source tarball each time) is to do `pip install https://github.com/dicompyler/dicompyler-core/archive/master.zip`

Either of those will work.

**Comment by bjce** [comment]
Many thanks for your answer @bastula. I could run `pip install https://github.com/dicompyler/dicompyler-core/archive/master.zip` without error message in an already existing environment. In this same environment I tried `$ dicompyler` without success (no command with this name). Do you have an idea of what could be a next step? Many thanks for your support and your time

**Comment by bastula** [comment]
I'm so sorry, that was for the `dicompyler-core` project/repository. I would probably just download the source zip file from the home page and use the `pip install -e` once you have extracted it. You will need Python 3 to run it.
