### ISSUE TITLE
Crash occurs when reading files from folder with non-ascii characters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bastula/dicompyler#83]
```
What steps will reproduce the problem?
1. Put any CT file in a folder named e.g. "test". Open the folder with 
Dicompyler and click select: The display window opens successfully.
2. Rename the folder to a name containing at least one non-standard ascii 
character, e.g. "testøæå"
3. Browse to the folder and press OK. Click Select to get the display window. 
Dicompyler crashes before reaching the display window.

What is the expected output? What do you see instead?
Expect to see the CT image(s). Instead we get the following crash report:
dicompyler.plugin: DEBUG: anonymize loaded
dicompyler.plugin: DEBUG: dvh loaded
dicompyler.plugin: DEBUG: treeview loaded
dicompyler.dicomgui: DEBUG: Reading: 
C:\github\temp\dicompyler_errorø\CT_fails_with_dicompyler_encoding.dcm
dicompyler: ERROR: Unhandled exception: Traceback (most recent call last):
  File "main.py", line 691, in Run
  File "threading.pyo", line 484, in run
  File "dicompyler\dicomgui.pyo", line 666, in GetPatientData
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 
31: ordinal not in range(128)

What version of the product are you using? On what operating system?
System: Windows
Version: ('XP', '5.1.2600', 'SP3', 'Multiprocessor Free')
Python Version: 2.6.6
dicompyler Version: 0.4.1-1

Please provide any additional information below.

```

Original issue reported on code.google.com by `chris.le...@gmail.com` on 23 Oct 2012 at 2:08
##

**Comment by Sogolumbo** [comment]
Please add a warning when selecting a folder with non-ascii characters in their name.
